# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gameScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(956, 718)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelJogador = QtWidgets.QLabel(self.centralwidget)
        self.labelJogador.setGeometry(QtCore.QRect(120, 70, 381, 41))
        self.labelJogador.setObjectName("labelJogador")
        self.labelDealer = QtWidgets.QLabel(self.centralwidget)
        self.labelDealer.setGeometry(QtCore.QRect(120, 220, 381, 41))
        self.labelDealer.setObjectName("labelDealer")
        self.btnComprar = QtWidgets.QPushButton(self.centralwidget)
        self.btnComprar.setGeometry(QtCore.QRect(330, 120, 75, 23))
        self.btnComprar.setObjectName("btnComprar")
        self.btnParar = QtWidgets.QPushButton(self.centralwidget)
        self.btnParar.setGeometry(QtCore.QRect(420, 120, 75, 23))
        self.btnParar.setObjectName("btnParar")
        self.labelCarta = QtWidgets.QLabel(self.centralwidget)
        self.labelCarta.setGeometry(QtCore.QRect(590, 70, 71, 91))
        self.labelCarta.setText("")
        self.labelCarta.setPixmap(QtGui.QPixmap("../baralhos/KE.png"))
        self.labelCarta.setScaledContents(True)
        self.labelCarta.setObjectName("labelCarta")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 956, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelJogador.setText(_translate("MainWindow", "Mão do jogador: "))
        self.labelDealer.setText(_translate("MainWindow", "Mão do dealer: "))
        self.btnComprar.setText(_translate("MainWindow", "Comprar"))
        self.btnParar.setText(_translate("MainWindow", "Parar"))
