# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastroUsuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 900)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelDataNascimento = QtWidgets.QLabel(self.centralwidget)
        self.labelDataNascimento.setGeometry(QtCore.QRect(490, 320, 171, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.labelDataNascimento.setFont(font)
        self.labelDataNascimento.setStyleSheet("border-radius: 16px;\n"
"backdrop-filter: blur(10.8px);")
        self.labelDataNascimento.setObjectName("labelDataNascimento")
        self.pushButtonEnviar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEnviar.setGeometry(QtCore.QRect(680, 560, 131, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.pushButtonEnviar.setFont(font)
        self.pushButtonEnviar.setStyleSheet("border-radius: 6px;\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #ccc;")
        self.pushButtonEnviar.setObjectName("pushButtonEnviar")
        self.dateEditDataNascimento = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEditDataNascimento.setGeometry(QtCore.QRect(490, 340, 371, 34))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.dateEditDataNascimento.setFont(font)
        self.dateEditDataNascimento.setStyleSheet("border-radius: 16px;\n"
"backdrop-filter: blur(10px);\n"
"border-radius: 8px;\n"
"border: 1px solid #ccc;")
        self.dateEditDataNascimento.setObjectName("dateEditDataNascimento")
        self.lineEditTelefone = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditTelefone.setGeometry(QtCore.QRect(490, 478, 371, 34))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.lineEditTelefone.setFont(font)
        self.lineEditTelefone.setStyleSheet("border-radius: 16px;\n"
"backdrop-filter: blur(10px);\n"
"border-radius: 8px;\n"
"border: 1px solid #ccc;")
        self.lineEditTelefone.setText("")
        self.lineEditTelefone.setObjectName("lineEditTelefone")
        self.labelDescricao = QtWidgets.QLabel(self.centralwidget)
        self.labelDescricao.setGeometry(QtCore.QRect(520, 70, 291, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        self.labelDescricao.setFont(font)
        self.labelDescricao.setStyleSheet("color: #fff;\n"
"border-style: solid;\n"
"border-color: red;\n"
"box-shadow: rgba(0, 0, 0, 0.56) 0px 22px 70px 4px;")
        self.labelDescricao.setObjectName("labelDescricao")
        self.labelTelefone = QtWidgets.QLabel(self.centralwidget)
        self.labelTelefone.setGeometry(QtCore.QRect(490, 460, 81, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.labelTelefone.setFont(font)
        self.labelTelefone.setStyleSheet("border-radius: 16px;\n"
"backdrop-filter: blur(10.8px);")
        self.labelTelefone.setObjectName("labelTelefone")
        self.lineEditNome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNome.setGeometry(QtCore.QRect(490, 270, 371, 34))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.lineEditNome.setFont(font)
        self.lineEditNome.setStyleSheet("border-radius: 16px;\n"
"backdrop-filter: blur(10px);\n"
"border-radius: 8px;\n"
"border: 1px solid #ccc;")
        self.lineEditNome.setText("")
        self.lineEditNome.setObjectName("lineEditNome")
        self.pushButtonVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonVoltar.setGeometry(QtCore.QRect(540, 560, 131, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.pushButtonVoltar.setFont(font)
        self.pushButtonVoltar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;\n"
"border: 1px solid #ccc;")
        self.pushButtonVoltar.setObjectName("pushButtonVoltar")
        self.labelEmail = QtWidgets.QLabel(self.centralwidget)
        self.labelEmail.setGeometry(QtCore.QRect(490, 390, 51, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.labelEmail.setFont(font)
        self.labelEmail.setStyleSheet("border-radius: 16px;\n"
"backdrop-filter: blur(10.8px);")
        self.labelEmail.setObjectName("labelEmail")
        self.lineEditEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditEmail.setGeometry(QtCore.QRect(490, 410, 371, 34))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.lineEditEmail.setFont(font)
        self.lineEditEmail.setStyleSheet("border-radius: 16px;\n"
"backdrop-filter: blur(10px);\n"
"border-radius: 8px;\n"
"border: 1px solid #ccc;")
        self.lineEditEmail.setText("")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1440, 900))
        self.label_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_3.setStyleSheet("")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../imagens/mesaFundo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.labelNome = QtWidgets.QLabel(self.centralwidget)
        self.labelNome.setGeometry(QtCore.QRect(490, 250, 61, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.labelNome.setFont(font)
        self.labelNome.setStyleSheet("border-radius: 16px;\n"
"backdrop-filter: blur(10.8px);")
        self.labelNome.setObjectName("labelNome")
        self.labelFundoClaro = QtWidgets.QLabel(self.centralwidget)
        self.labelFundoClaro.setGeometry(QtCore.QRect(440, 210, 471, 421))
        self.labelFundoClaro.setStyleSheet("border-radius: 16px;\n"
"background: rgba(255, 250, 250, 0.9);")
        self.labelFundoClaro.setText("")
        self.labelFundoClaro.setObjectName("labelFundoClaro")
        self.label_3.raise_()
        self.labelFundoClaro.raise_()
        self.lineEditTelefone.raise_()
        self.lineEditEmail.raise_()
        self.dateEditDataNascimento.raise_()
        self.labelDataNascimento.raise_()
        self.labelEmail.raise_()
        self.labelTelefone.raise_()
        self.lineEditNome.raise_()
        self.labelNome.raise_()
        self.labelDescricao.raise_()
        self.pushButtonVoltar.raise_()
        self.pushButtonEnviar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelDataNascimento.setText(_translate("MainWindow", "Data de Nascimento:"))
        self.pushButtonEnviar.setText(_translate("MainWindow", "Enviar"))
        self.labelDescricao.setText(_translate("MainWindow", "Cadastro de Usuário "))
        self.labelTelefone.setText(_translate("MainWindow", "Telefone:"))
        self.pushButtonVoltar.setText(_translate("MainWindow", "Voltar"))
        self.labelEmail.setText(_translate("MainWindow", "Email:"))
        self.labelNome.setText(_translate("MainWindow", "Nome:"))
