# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1333, 849)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 1341, 821))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../imagens/mesaFundo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 121, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("unnamed.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButtonJogar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonJogar.setGeometry(QtCore.QRect(20, 590, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.pushButtonJogar.setFont(font)
        self.pushButtonJogar.setAutoFillBackground(False)
        self.pushButtonJogar.setStyleSheet("background-color:#0ba4eb;\n"
"color:#ffffff;\n"
"border-radius:20px;")
        self.pushButtonJogar.setObjectName("pushButtonJogar")
        self.labelLogo = QtWidgets.QLabel(self.centralwidget)
        self.labelLogo.setGeometry(QtCore.QRect(1200, 10, 121, 121))
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap("../imagens/logo21.png"))
        self.labelLogo.setScaledContents(True)
        self.labelLogo.setObjectName("labelLogo")
        self.pushButtonComoJogar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonComoJogar.setGeometry(QtCore.QRect(20, 660, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.pushButtonComoJogar.setFont(font)
        self.pushButtonComoJogar.setAutoFillBackground(False)
        self.pushButtonComoJogar.setStyleSheet("background-color:#0ba4eb;\n"
"color:#ffffff;\n"
"border-radius:20px;")
        self.pushButtonComoJogar.setObjectName("pushButtonComoJogar")
        self.pushButtonCadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCadastrar.setGeometry(QtCore.QRect(20, 730, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.pushButtonCadastrar.setFont(font)
        self.pushButtonCadastrar.setAutoFillBackground(False)
        self.pushButtonCadastrar.setStyleSheet("background-color:#0ba4eb;\n"
"color:#ffffff;\n"
"border-radius:20px;")
        self.pushButtonCadastrar.setObjectName("pushButtonCadastrar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1333, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonJogar.setText(_translate("MainWindow", "Jogar"))
        self.pushButtonComoJogar.setText(_translate("MainWindow", "Como jogar"))
        self.pushButtonCadastrar.setText(_translate("MainWindow", "Cadastrar"))
